export type DeclarationFilters = {
  declRegDate?: string | null;
  declEndDate?: string | null;
  number?: string | null;
  idDeclaration?: number | null;
  idStatus?: number | null;
  inn?: string | null;
  applicantFullName?: string | null;
  applicantShortName?: string | null;
  manufacturerShortName?: string | null;
  manufacturerFullName?: string | null;
  productFullName?: string | null;
  testingLabsFullName?: string | null;
  testingLabsRegNumber?: string | null;
  certificationAuthorityFullName?: string | null;
  certificationAuthorityAttestatRegNumber?: string | null;
  status?: string | null;
  tnvedName?: string | null;
  tnvedCode?: string | null;
  validationFormNormDocName?: string | null;
  validationFormNormDocNum?: string | null;
  validationObjectType?: string | null;
  conformityDocType?: string | null;
  contactType?: string | null;
  oksm?: string | null;
  fiasAddrobj?: string | null;
  page?: number | null;
};
