import mongoose from "mongoose";
const { Schema } = mongoose;

export const certificateSchema = new Schema({
  id: { type: Number, index: true, unique: true },
  idStatus: { type: Number, index: true },
  number: { type: String, index: true },
  date: { type: String, index: true },
  endDate: { type: String, index: true },
  blankNumber: { type: String, index: true },
  technicalReglaments: { type: String, index: true },
  group: { type: String, index: true },
  certType: { type: String, index: true },
  certObjectType: { type: String, index: true },
  applicantLegalSubjectType: { type: String, index: true },
  applicantType: { type: String, index: true },
  applicantName: { type: String, index: true },
  applicantOpf: { type: String, index: true },
  applicantFilialFullNames: { type: String, index: true },
  manufacterLegalSubjectType: { type: String, index: true },
  manufacterType: { type: String, index: true },
  manufacterName: { type: String, index: true },
  manufacterOpf: { type: String, index: true },
  manufacterFilialFullNames: { type: String, index: true },
  idRalCertificationAuthority: { type: Number, index: true },
  certificationAuthorityAttestatRegNumber: { type: String },
  productOrig: { type: String },
  productFullName: { type: String, index: true },
  productBatchSize: { type: String, index: true },
  productIdentificationName: { type: String, index: true },
  productIdentificationType: { type: String, index: true },
  productIdentificationTrademark: { type: String, index: true },
  productIdentificationModel: { type: String, index: true },
  productIdentificationArticle: { type: String, index: true },
  productIdentificationSort: { type: String, index: true },
  productIdentificationGtin: { type: String, index: true },
  expertFio: { type: String, index: true },
  expertSnils: { type: String },
});
